name: Package on tag

on:
  push:
    tags:
      - 'v*'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Build extension
        run: npm run build
      - name: Install web-ext
        run: |
          npm install -g web-ext
      - name: Sign files
        run: |
          web-ext sign --api-key $MOZILLA_API_KEY --api-secret $MOZILLA_API_SECRET --channel unlisted && mv web-ext-artifacts/*.xpi aw-watcher-web.xpi
        env:
          MOZILLA_API_KEY: ${{ secrets.MOZILLA_API_KEY }}
          MOZILLA_API_SECRET: ${{ secrets.MOZILLA_API_SECRET }}
      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: aw-watcher-web.xpi